[package]
name = "compiler"
edition = "2024"
version.workspace = true

[dependencies]
parserc = "^0.10"
memchr = { version = "2.7.6"}
thiserror = "2.0.17"
serde = { version = "1.0.228", optional = true }

[features]
serde = ["dep:serde","serde/derive"]
